### ISSUE TITLE
Windows readdir Error

### ISSUE THREAD

**Issue by Enisada** [tcpaddock/shiplot#12]
Hello, I am using the latest version, 1.0.0-beta.2 on Windows Server 2022. I get the following error when trying to use the network function. I think it is either bug or a syntax issue.

C:\Users\Administrator\Desktop>shiplot.exe run --maxThreads=12 --stagingPaths="E:\CNFTs\*" --client.enabled=true --client.serverIp="192.168.0.143"
2023/04/15 08:37:23 INFO Creating worker pool with max size 12
2023/04/15 08:37:23 INFO Starting file system watcher
2023/04/15 08:37:23 INFO Path added to watcher name=E:\CNFTs\plot-k32-c07-2023-04-01-08-00-9626d437da5f87da851566e05df4e88eb11c5c3945b42fba2fdd52e22c480205.plot
Error: readdir E:\CNFTs\plot-k32-c07-2023-04-01-08-00-9626d437da5f87da851566e05df4e88eb11c5c3945b42fba2fdd52e22c480205.plot: The system cannot find the path specified.

**Comment by tcpaddock** [comment]
I'll try to replicate. In the mean time, can you try setting `--stagingPaths="E:\CNFTs\*"`?

**Comment by Enisada** [comment]
Thanks for the quick reply, same result with the suggested setting.

C:\Users\Administrator\Desktop>shiplot.exe run --maxThreads=12 --stagingPaths="E:\CNFTs\*" --client.enabled=true --client.serverIp="192.168.0.143"
2023/04/15 09:08:17 INFO Creating worker pool with max size 12
2023/04/15 09:08:17 INFO Starting file system watcher
2023/04/15 09:08:17 INFO Path added to watcher name=E:\CNFTs\plot-k32-c07-2023-04-01-09-03-418d92b841e4ecba21b06474a0afb38c4f74c18758791a09fcc17a05eead87eb.plot
Error: readdir E:\CNFTs\plot-k32-c07-2023-04-01-09-03-418d92b841e4ecba21b06474a0afb38c4f74c18758791a09fcc17a05eead87eb.plot: The system cannot find the path specified.

**Comment by Enisada** [comment]
Git hub is removing that slash when I post it here, but it is the setting I am using.

**Comment by tcpaddock** [comment]
> Git hub is removing that slash when I post it here, but it is the setting I am using.

That makes sense now!

Can you try removing the '*'?

**Comment by Enisada** [comment]
I removed the slash and the star, working with this --stagingPaths="E:\CNFTs"

Thanks!

**Comment by tcpaddock** [comment]
Thanks for confirming. I was not able to replicate on Windows 11 but I was able to replicate on Server 2016:

```
shiplot.exe run --maxThreads=12 --stagingPaths="G:\CNFTs\*" --client.enabled=true --client.serverIp="192.168.0.143"
2023/04/15 12:33:31 INFO Creating worker pool with max size 12
2023/04/15 12:33:31 INFO Starting file system watcher
2023/04/15 12:33:31 INFO Path added to watcher name=G:\CNFTs\plot-k32-c07-2023-04-01-08-00-9626d437da5f87da851566e05df4e88eb11c5c3945b42fba2fdd52e22c480205.plot
Error: readdir G:\CNFTs\plot-k32-c07-2023-04-01-08-00-9626d437da5f87da851566e05df4e88eb11c5c3945b42fba2fdd52e22c480205.plot: The system cannot find the path specified.
```

I'll add a fix since the glob should still work even if not required in your case.
