### ISSUE TITLE
Watcher auto adds lost+found directory

### ISSUE THREAD

**Issue by Enisada** [tcpaddock/shiplot#13]
Hello,

Seems every so often my Plotter in Ubuntu will add this directory and stop shipping plots. I have three others machines and they don't do this.

2023/05/07 05:55:13 INFO Successfully uploaded /media/threadripper/Plots/Plots/plot-k32-c07-2023-05-06-21-52-d24081ed32b5be8ed6ff3e16bda073dc5197ad39a934b2693ce57eb4371ae622.plot written=83759595520 time=7m50.679933574s
2023/05/07 05:55:13 INFO Uploading /media/threadripper/Plots/Plots/plot-k32-c07-2023-05-06-21-55-c162a89a1cba4f5e3c63a56b19125b3bc38f71312c46c42ebe9aec9e022cf9e0.plot
2023/05/07 05:55:13 INFO Path added to watcher name=/media/threadripper/Plots
2023/05/07 05:55:13 INFO Path added to watcher name=/media/threadripper/Plots/lost+found
Error: permission denied

**Comment by tcpaddock** [comment]
Please try [v1.0.0-beta.4](https://github.com/tcpaddock/shiplot/releases/tag/v1.0.0-beta.4).

**Comment by Enisada** [comment]
Thanks running the latest version now.
